services:
  contact-api:
    image: contact-api
    container_name: contact-api
    build:
      context: . # contexte d'execution du Dockerfile
      dockerfile: src/Contacts.Api/Dockerfile # chemin du Dockerfile
    ports: # mapping du port machine, avec le port dans le container 
      - 80:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://contact-db:27017
    volumes:
      - ./src/Contacts.Api/contacts.json:/app/contacts.json
    depends_on:
      - contact-db

  contact-db:
    image: mongo:latest
    container_name: contact-db
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: