services:
  db:
    image: postgres:17.2
    container_name: myfitjob-db
    restart: always
    environment:
      POSTGRES_USER: myfitjob
      POSTGRES_PASSWORD: myfitjobpass
      POSTGRES_DB: myfitjobdb
      # setting these means when you exec in psql, you don't need to specify the db name
      PGDATABASE: myfitjobdb
      PGUSER: myfitjob
      PGPASSWORD: myfitjobpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./src/MyFITJob.Api
      dockerfile: Dockerfile
      target: prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myfitjobdb;Username=myfitjob;Password=myfitjobpass
    depends_on:
      - db

  frontend:
    build:
      context: src/MyFITJob.Frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src/MyFITJob.Frontend:/app:cached
      - /app/node_modules  # pour isoler les dépendances
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    environment:
      NODE_ENV: development

  nginx:
    image: nginx:latest
    container_name: myfitjob-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    cpus: 0.2
    mem_limit: 128m

# Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: myfitjob-prometheus-workload
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    cpus: 0.5
    mem_limit: 512m

  grafana:
    image: grafana/grafana:latest
    container_name: myfitjob-grafana-workload
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    cpus: 0.5
    mem_limit: 512m

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: myfitjob-postgres-exporter-workload
    environment:
      - DATA_SOURCE_NAME=postgresql://myfitjob:myfitjobpass@db:5432/myfitjobdb?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db
    cpus: 0.2
    mem_limit: 256m

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: myfitjob-nginx-exporter
    command:
      - --nginx.scrape-uri=http://frontend/nginx_status
    ports:
      - "9113:9113"
    depends_on:
      - frontend
    cpus: 0.1
    mem_limit: 128m

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: 